
export const QUESTIONS: string[] = [
  // Lighthearted Icebreakers (50)
  "If you could have any superpower, what would it be and why?",
  "What's the weirdest food you've ever eaten?",
  "What's your go-to karaoke song?",
  "If you were an animal, what would you be?",
  "What's a small thing that makes you unaccountably happy?",
  "What's the best concert you've ever been to?",
  "What's your most useless talent?",
  "If you could time travel, would you go to the past or the future?",
  "What's your favorite board game or card game?",
  "What's the most ridiculous thing you've ever bought?",
  "Who was your first celebrity crush?",
  "What's your favorite season and why?",
  "Are you a morning person or a night owl?",
  "What's a movie you can watch over and over again?",
  "If you had to eat one meal for the rest of your life, what would it be?",
  "What's the funniest joke you know by heart?",
  "What was your favorite cartoon as a kid?",
  "If you could instantly become an expert in something, what would it be?",
  "What's your biggest pet peeve?",
  "What's your favorite type of dessert?",
  "Beach vacation or mountain getaway?",
  "What's a weird habit you have?",
  "What's the best piece of advice you've ever received?",
  "If you could meet any historical figure, who would it be?",
  "What's the silliest thing you're afraid of?",
  "What's your dream car?",
  "What's one thing you're really good at?",
  "Do you prefer coffee or tea?",
  "What's a book that changed your perspective on something?",
  "What's the most spontaneous thing you've ever done?",
  "What's your favorite smell?",
  "If you could have dinner with any three people, living or dead, who would they be?",
  "What's a skill you'd love to learn?",
  "What's your spirit animal?",
  "What's your ideal way to spend a rainy day?",
  "What's the most beautiful place you've ever visited?",
  "What's your favorite holiday?",
  "If you had a warning label, what would it say?",
  "What's something you believed for way too long as a child?",
  "What's your favorite guilty pleasure TV show?",
  "What's your favorite way to exercise?",
  "What's a weird food combination you love?",
  "What's the best gift you've ever given or received?",
  "If you could live in any fictional world, which one would it be?",
  "What's your signature dance move?",
  "What's one thing that can always make you laugh?",
  "What's your favorite thing about your best friend?",
  "If you opened a restaurant, what kind of food would you serve?",
  "What's a song that always gets you on the dance floor?",
  "What's the dumbest way you've ever been injured?",
  // Personal & Thought-Provoking (75)
  "What are you most proud of in your life so far?",
  "What is one of your biggest fears?",
  "What's something you've never told anyone before?",
  "What does 'success' mean to you?",
  "What's a challenge you've overcome that made you stronger?",
  "What's one thing you would change about yourself?",
  "What do you value most in a friendship?",
  "What's a dream you've had for a long time but haven't pursued yet?",
  "How do you deal with stress or difficult situations?",
  "What's one of your happiest memories?",
  "What's a lesson you had to learn the hard way?",
  "Who has been the most influential person in your life?",
  "What are you most grateful for right now?",
  "What's something you're currently working on to improve in your life?",
  "Do you believe in fate or free will?",
  "What's something that makes you feel truly alive?",
  "What's a mistake you've made that you've forgiven yourself for?",
  "How do you define happiness?",
  "What is your love language?",
  "What's your biggest insecurity?",
  "What's something you wish more people knew about you?",
  "What's a quality you admire in others?",
  "What's your relationship with your family like?",
  "What's something you're passionate about?",
  "If you could give your younger self one piece of advice, what would it be?",
  "What's your biggest deal-breaker in a relationship?",
  "What does a perfect day look like to you?",
  "What's something you feel you missed out on in childhood?",
  "How do you show love to the people you care about?",
  "What's a belief you hold that many people disagree with?",
  "What's your greatest strength and your greatest weakness?",
  "When do you feel most like yourself?",
  "What's an experience that completely changed your outlook on life?",
  "What's one thing you want to accomplish in the next year?",
  "What's the meaning of life, in your opinion?",
  "How do you handle conflict?",
  "What's a promise you made to yourself that you've kept?",
  "What's your favorite thing about your personality?",
  "What's something that always brings a tear to your eye?",
  "What's the most important quality in a partner for you?",
  "What's a time you felt truly understood by someone?",
  "What do you think happens after we die?",
  "What's a compliment that has always stuck with you?",
  "What's a boundary you're proud of setting?",
  "What's an assumption people often make about you?",
  "What's a topic you could talk about for hours?",
  "When you're feeling down, what's your go-to comfort activity?",
  "What's a risk you're glad you took?",
  "What are you looking for in your life right now?",
  "What's a failure that taught you something important?",
  "What legacy do you want to leave behind?",
  "How do you recharge your social battery?",
  "What is something you're afraid to ask for in a relationship?",
  "What's the most significant thing you've done for someone else?",
  "What's a piece of art (book, movie, painting) that has deeply moved you?",
  "What does vulnerability mean to you?",
  "What's a secret hope you have for the future?",
  "What's your definition of a 'good life'?",
  "How have your priorities changed over the last five years?",
  "What's something you've learned about love?",
  "What's an aspect of your culture or heritage that's important to you?",
  "What's something you're still trying to figure out?",
  "What's a moment you felt completely at peace?",
  "What's something you do just for you?",
  "How important is physical touch to you in a relationship?",
  "What's a time you felt really brave?",
  "What's your relationship with money?",
  "What's a quality you're trying to cultivate in yourself?",
  "What's a recurring theme in your life?",
  "What do you think is your purpose?",
  "How do you like to be comforted when you're upset?",
  "What's one thing you're not willing to compromise on?",
  "What's a memory you'll cherish forever?",
  // Deeper & Intimate (50)
  "What's your biggest regret?",
  "Describe a time you've felt heartbroken.",
  "What's a part of you that you keep hidden from most people?",
  "What's the most romantic thing someone has ever done for you?",
  "What's your deepest fear about being in a relationship?",
  "What's a fantasy you've never shared with a partner?",
  "What makes you feel desired?",
  "What's a physical feature you find most attractive in a partner?",
  "What's your view on monogamy?",
  "What's an experience that made you question everything?",
  "What does intimacy mean to you, beyond the physical?",
  "What's something you need from a partner to feel secure?",
  "What's your biggest turn-on that isn't physical?",
  "What's something you're afraid of losing?",
  "Have you ever been in love? How did you know?",
  "What's a past relationship that taught you a significant lesson?",
  "How do you feel about public displays of affection?",
  "What's a secret you've kept from a past partner?",
  "What is your idea of a perfect, romantic evening?",
  "What's a non-negotiable for you in the bedroom?",
  "What's the most vulnerable you've ever felt with someone?",
  "What's something you've never had the courage to try, but want to?",
  "What's a boundary you've had to enforce in a past relationship?",
  "What's your favorite way to be touched?",
  "How do you approach disagreements about sex with a partner?",
  "What's a time you felt truly desired?",
  "What's your opinion on sharing secrets about your past?",
  "What is something that would make you feel emotionally unsafe in a relationship?",
  "What is the most intimate thing you can do with a partner without being physical?",
  "What's a role-play scenario you've always been curious about?",
  "What's the most adventurous thing you've done sexually?",
  "How important is sexual compatibility in a long-term relationship?",
  "What's a physical insecurity you have?",
  "What's your favorite part of your own body?",
  "What is a surefire way for a partner to make you feel loved and appreciated?",
  "What's a time you felt jealous and how did you handle it?",
  "What's a question you've always wanted to ask a partner but never have?",
  "What does emotional cheating mean to you?",
  "What's your favorite memory of us (if applicable)?",
  "What's an experience you want to share with a partner?",
  "What's something you're still healing from?",
  "What's the most important thing for emotional connection?",
  "What's a 'little thing' that means a lot to you in a relationship?",
  "When did you last cry and what was it about?",
  "What's a fear you have about our future (if applicable)?",
  "What's something you admire about my character?",
  "What is something I do that makes you feel safe?",
  "What is a fantasy of yours that involves a place, not just an act?",
  "How do you define 'making love'?",
  "What's a lie you've told that you regret?",
  // Sultry & Flirty (25)
  "What's the most attractive thing I'm wearing right now?",
  "If you could kiss me anywhere right now, where would it be?",
  "What's a song that makes you think of me?",
  "Describe your perfect kiss.",
  "What's your biggest turn-on?",
  "What's your biggest turn-off?",
  "What's an outfit you'd love to see me in?",
  "What's a secret talent you have that might be surprising?",
  "If we had 24 hours with no responsibilities, what would we do?",
  "What's your favorite non-physical quality about me?",
  "What's the sexiest thing about confidence?",
  "What's a movie scene that always gets you in the mood?",
  "Lights on or lights off?",
  "What's something you find unexpectedly sexy?",
  "What's the most daring place you've ever wanted to be intimate?",
  "Whisper your favorite compliment to give me in my ear.",
  "What's your favorite sound that I make?",
  "If you were to describe my scent, what would you say?",
  "What's the first thing you notice when you look at me?",
  "What's a guilty pleasure you'd want to share with me?",
  "Slow and sensual, or fast and passionate?",
  "What's the most romantic text message you've ever received?",
  "What is one word you would use to describe our chemistry?",
  "If you could plan our next date, what would we be doing?",
  "What's a fantasy you've always been too shy to share?"
];
